---
title: "assignment5"
author: "Liu Yuliang"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
library(tidyverse)
library(readr)
gapminder <- read_delim("gapminder.csv")
```
```{r}
num_of_rows <- nrow(gapminder)
num_of_rows
num_of_cols <- ncol(gapminder)
num_of_cols
```
```{r}
gapminder %>% 
  head(5)
```
The data looks good.
```{r}
iso3_count <- length(unique(gapminder$iso3))
iso2_count <- length(unique(gapminder$iso2))
name_count <- length(unique(gapminder$name))
```
There are `r iso3_count`, `r iso2_count` and `r name_count` countries in
iso3, iso2 and name, respectively.

```{r}
multi_name_iso2 <- gapminder %>%
  filter(is.na(iso3) & is.na(name)) %>%
  group_by(iso2) %>%
  summarize(distinct_name = n_distinct(iso2)) %>% 
  print()

multi_name_name <- gapminder %>%
  filter(is.na(iso2) & is.na(iso3)) %>%
  group_by(name) %>%
  summarize(distinct_name = n_distinct(name)) %>% 
  print()

multi_name_iso3 <- gapminder %>%
  filter(is.na(iso2) & is.na(name)) %>%
  group_by(iso3) %>%
  summarize(distinct_name = n_distinct(iso3)) %>% 
  print()
```
```{r}
min_year <- gapminder %>% 
  filter(!is.na(time)) %>% 
  summarize(min_year = min(time)) %>% 
  print()
max_year <- gapminder %>% 
  filter(!is.na(time)) %>% 
  summarize(max_year = max(time)) %>% 
  print()
```
```{r}
missing_co2 <- gapminder %>% 
  filter(!is.na(time)) %>% 
  group_by(time) %>% 
  summarize(missing_co2 = sum(is.na(co2))) %>%
  arrange(desc(missing_co2))

show_missing_co2 <- missing_co2 %>% 
  head() %>% 
  print()

missing_co2_PC <- gapminder %>% 
  filter(!is.na(time)) %>% 
  group_by(time) %>% 
  summarize(missing_co2_PC = sum(is.na(co2_PC))) %>%
  arrange(desc(missing_co2_PC))
show_missing_co2_PC <- missing_co2_PC %>% 
  head() %>% 
  print()
```
Year 2017, 2018 and 2019 have the most missing data that count for 217 NA values.
```{r}
filter_countries <- gapminder %>% 
  filter(name == "United States of America" | name == "China" | name == "India"
         | name == "Germany" | name == "Iraq") %>% 
  filter(!is.na(co2))

ggplot(filter_countries, aes(x = name, y = co2, color = name)) +
  geom_histogram() +
  labs(title = "Total CO2 Emissions Over Time",
       x = "Year",
       y = "CO2 Emissions (metric tons per capita)",
       color = "Country") +
  theme_bw()
```






